---
title: "20200404~~~!"
author: "李宜遠"
date: "4/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## list

```{r}
vectorExample <- c(2, 6, 7)
listExample <- list(2, 6, 7)

print(vectorExample)
print(listExample)
```

每個元素值可以是不同type的物件值
```{r}
# 用vector儲存
c("2020-03-31T13:40:55Z",
  "一芳",
  "2",
  "水果茶")

# 用list儲存
library(lubridate)
list(
  ymd_hms("2020-03-31T13:40:55Z"), # date/time
  "一芳", # character
  2, # numeric
  "水果茶" # character
  )
print('小明交易1')
```

物件值可以是vector形式，也可以list
```{r}
# 用vector
c(
  c("108學年第1學期", "高級會計學", "高等統計學"), #向量1
  c("108學年第2學期", "食在拉丁美洲") #向量2
)
```

```{r}
# 用list
list(
  c("108學年第1學期", "高級會計學", "高等統計學"), #向量1
  c("108學年第2學期", "食在拉丁美洲") #向量2
)
```
```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```


```{r}
# list含兩個lists
`小明108學年課表C` <- list(
  list(
    c("108-1"),
    c("高級會計學","高等統計學")
    ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```


物件值可以取名
```{r}
`小明108學年課表Ｄ` <- list(
  `上學期`=list(
    semester=c("108-1"),
    courses=c("高級會計學","高等統計學")
    ),
  `下學期`=list(
    semester=c("108-2"),
    courses=c("食在拉丁美洲")
  )
)
print(`小明108學年課表Ｄ`)
```


## Github Commit

```{r}
commit <- list(
  author = list(
   name=" Martin老師",
  email=" mtlin@gm.ntpu.edu.tw",
  time=ymd_hms("2020-03-25T07:17:40Z")),
  committer = list(
    name="emilyluckey",
    email="emily007@gmail.com",
   time=ymd_hms("2020-03-26T08:18:40Z")
   ),
  message = "update"
)
print(commit)
```






```{r}
browseURL("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") 
```


```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
```


#今明天氣預報

```{r}
`今明天氣預報`<-list(
  today=("2020-03-31"),
  tomorrow=("2020-04-01"),
  `台北市`=list(
    highesttemp=25,   #若等號左邊是打中文“最高氣溫”就要用反頓點！
    lowesttemp=18
  ),
  `新北市`=list(
    highesttemp=24,
    lowesttemp=15
  )
)

print(`今明天氣預報`)
```


```{r}
library(lubridate)
`今明天氣預報`<-list(     #存成某值（寫仔list之前）：反頓點
  `日期`=list(
    ymd("2020-03-31","2020-04-01")
  ),           # element1 ends here
  `台北市`=list(
    "最高氣溫"=25,
    "最低氣溫"=18
  ),           # element2 ends here
  `新北市`=list(
    "最高氣溫"=24,
    "最低氣溫"=15
  )           # element3 ends here
)

print(`今明天氣預報`)     #呼叫存的值：反頓點
```







## 3.7

```{r}
save(commit,listExample, `小明108學年課表Ｄ`, fule="today.Rda")
```

```{r}
load("today.Rda")
```






```{r}


```

```{r}


```

```{r}


```

```{r}

```




