---
title: '20200623'
author: "李宜遠"
date: "6/23/2020"
output: html_document
---
## 5.3.4 switch
```{r}
library(lubridate)  ##日期時間
library(stringr)  ##字串
library(purrr) ##map
library(magrittr)  ##pipe
```


另一種條件式執行常用在condition種類煩雜或要全部以「是/否」問句來切出所有互斥condition情境不容易設計時。

*condition改成用文字描述，即conditionExpression。

*不同conditionExpression與對應body內容改成使用一對對的:

"conditionExpression文字"={body 內容} 的name=value pair

Copy

```{r}
switch(實現的conditionExpression,
       "conditionExpression1"= {    },
       "conditionExpression2"= {    },
       :
       :
       "conditionExpressionN"= {    },
       {    })
```



Mathematical function

















```{r}
n <- 5
if( n%%2==1){
  fvalue= -(n+1)/2
}else{
  fvalue= n/2
}
print(fvalue)
```

```{r}
n<- 540

conditionExpression_outcome=
  ifelse(n %% 2==0, "even", "odd") 

switch(
  conditionExpression_outcome,
  "even"={fvalue <- n/2}, # 偶數
  "odd"=fvalue <- -(n+1)/2, # 奇數；只有一行指令可省略{}
  warning("n要整數喔")  
)

print(fvalue)
```

```{r}
grades <- c(52, 77, 59, 88, 90)

ifelse(grades >= 60, "及格", "不及格")
```

在R裡`{...}`（大括號, brace）：

若只有一行指令則`{}`符號可省略。

依照上一個特性，function(...)`{....}`的body若只有一行指令可省略`{...}`改寫成function(...) ..., 只是要小心body … 要接在function(...)之後不可換行。

```{r}
miniFun <- function(){
  lubridate::now()
}
miniFun()
```

```{r}
miniFun2 <- function() lubridate::now()
miniFun2()
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
```{r}

```

```{r}

```

